### ISSUE TITLE
NoneType object has no attribute lower

### ISSUE THREAD

**Issue by Muneer91** [RileyXX/PlexPreferNonForcedSubs#17]
### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Bug Description

Ran the script on my Plex collection, goes fine until it comes across a movie I’m assuming is probably Avatar 2. 
then throws this error:

`Traceback (most recent call last):
File "/home/pi/.local/lib/python3.9/site-packages/PlexPr eferNonForcedSubs/PlexPreferNonForcedSubs.py", line 58, in main
non_forced_english_subs = [stream for stream in englis
h_subs if stream is not None and (not stream.forced or (' f orced' not in getattr (stream, "title', ,"').lower () )) 1
File "/home/pi/.local/lib/python3.9/site-packages/PlexPr eferNonForcedSubs/PlexPreferNonForcedSubs.py", , line 58, in ‹listcomp>
non_forced_english_subs = [stream for stream in englis
h_subs if stream is not None and (not stream. forced or ('f orced' not in getattr (stream,
'title', "').lower ()))]
AttributeError: 'NoneType' object has no attribute 'lower'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/home/pi/. local/bin/PlexPreferNonForcedSubs", line 8, in <module>
sys.exit(main ())
File "/home/pi/.local/lib/python3.9/site-packages/PlexPr eferNonForcedSubs/PlexPreferNonForcedSubs.py", line 109,
n main errorHandling. report_error (error_message)
NameError: name 'errorHandling' is not defined `

### Environment

OS : raspbian bullseye
Using pip install method: yes

### Screenshots

![IMG_0762](https://github.com/RileyXX/PlexPreferNonForcedSubs/assets/88431352/5c04f313-bb80-430e-b635-86fc8517937d)

**Comment by RileyXX** [comment]
Hi, thanks for the detailed bug report! I will be investigating this issue. I have implemented 2 fixes in the latest patch which should fix these issues. You can see the details of that patch [here](https://github.com/RileyXX/PlexPreferNonForcedSubs/releases/tag/v2.1.8). 

You can update to the latest version using the following:
````
python -m pip install PlexPreferNonForcedSubs --upgrade
````

If you are still getting this error on the latest version let me know and I will investigate further. Thanks!

**Comment by Muneer91** [comment]
Hi, I can confirm it's all working now. Thanks so much for your hard work and swift resolution. Much appreciated!
