### ISSUE TITLE
[Feature Request]: Set first English subtitle stream as default, even when there are no Forced subtitle streams

### ISSUE THREAD

**Issue by stevehoek** [RileyXX/PlexPreferNonForcedSubs#19]
### Is there already a request for your feature?

- [X] I have checked older issues, open and closed

### Feature Request

I may misunderstand the point of this script, but I was hoping it would set each movie and show to have its first English subtitle stream as default, so that when I play it I don't have to navigate the Player UI to turn on subtitles.

It seems to only do this when there is also a Forced subtitle stream.

Can some config options be added change the logic to behave this way?

Some other nice-to-haves:
- config to only do movies or shows or both
- ability to run against a specific movie or show

**Comment by RileyXX** [comment]
Hi, these are some great ideas!

> I was hoping it would set each movie and show to have its first English subtitle stream as default, so that when I play it I don't have to navigate the Player UI to turn on subtitles.

This can be accomplished by setting your default subtitle settings in Plex under Settings > Account > Audio & Subtitle Settings. 

Still, it's a good idea and definitely something I might consider adding. The downside to using the script to do this would be, when you manually set a subtitle to None in Plex, it will be overruled with an English subtitle track next time the script is run. Which may or may not be the behavior a user is looking for. 

See screenshot:
<img width="790" alt="05-28-2023_324" src="https://github.com/RileyXX/PlexPreferNonForcedSubs/assets/49823202/7e6b69d3-52c9-40f2-8386-20d3bd5c04b0">

> Some other nice-to-haves:
> - config to only do movies or shows or both
> - ability to run against a specific movie or show

These are also great ideas! I think I will make plans to add these features in a future update.
